modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/SilentChaos512/ScalingHealth"
displayURL="https://minecraft.curseforge.com/projects/scaling-health"
logoFile="examplemod.png"
credits="SilentChaos512"
authors="SilentChaos512"

[[mods]]
    modId="scalinghealth"
    version="${file.jarVersion}"
    displayName="Scaling Health"
    description='''
    Extra health and damage for players and mobs. Highly customizable difficulty system.
    '''

[[dependencies.scalinghealth]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalinghealth]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalinghealth]]
    modId="silentlib"
    mandatory=true
    versionRange="[4,)"
    ordering="NONE"
    side="BOTH"