modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
issueTrackerURL="https://github.com/SilentChaos512/ScalingHealth"
displayURL="https://minecraft.curseforge.com/projects/scaling-health"
credits="SilentChaos512, Cyborgmas"
authors="SilentChaos512"

[[mods]]
    modId="scalinghealth"
    version="${file.jarVersion}"
    displayName="Scaling Health"
    description='''Extra health and damage for players and mobs. Highly customizable difficulty system.'''
[[dependencies.scalinghealth]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalinghealth]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scalinghealth]]
    modId="silentlib"
    mandatory=true
    versionRange="[4.8,)"
    ordering="NONE"
    side="BOTH"